openapi: 3.0.3
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro do consultório.
  version: 0.0.1
  termsOfService: http://mockapi.io
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: http://mockapi.io
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação externa
  url: http://mockapi.io

servers: 
- url: https://6650a8c5ec9b4a4a6032e9bf.mockapi.io/
  description: API de QA
- url: ""
  description: API de PROD
paths:
  /especialidades:
    get:
      summary: Recupera todas as especialidades.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    descricao:
                      type: string
                      
  /especialidades/{id}:
    parameters: 
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Recupera uma especialidade por id.
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                    type: string
        404:
          description: Especialidade não encontrada
          content:
            application/json:
              example: "Not found"