openapi: 3.0.3
info:
  title: API de consultório
  description: API para controlar médicos e suas especialidades dentro do consultório.
  version: 0.0.1
  termsOfService: http://mockapi.io
  contact:
    name: Suporte a Devs
    email: contato@example.com
    url: http://mockapi.io
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação externa
  url: http://mockapi.io
